CREATE OR ALTER PROCEDURE SP_DIM_PLANO(@DATA_CARGA DATETIME)
AS
BEGIN
	DECLARE @COD INT, @NOME VARCHAR(100), @VALOR NUMERIC(10,2)

	DECLARE C_PLANO CURSOR FOR 
	SELECT COD_PLANO, NOME, VALOR
	FROM TB_AUX_PLANO
	WHERE @DATA_CARGA = DATA_CARGA

	OPEN C_PLANO

	FETCH C_PLANO INTO @COD, @NOME, @VALOR

	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		
		IF(EXISTS(SELECT * FROM DIM_PLANO WHERE COD_PLANO = @COD))
		BEGIN
			UPDATE DIM_PLANO
			SET	NOME = @NOME
			WHERE COD_PLANO = @COD

			IF @VALOR <> (SELECT VALOR FROM DIM_PLANO WHERE COD_PLANO = @COD AND FL_CORRENTE = 'SIM')
			BEGIN
				UPDATE DIM_PLANO
				SET FL_CORRENTE = 'NAO', DT_FIM = DATEADD(DD, -1, @DATA_CARGA)
				WHERE COD_PLANO = @COD

				INSERT INTO DIM_PLANO
				VALUES(@COD, @NOME, @VALOR, @DATA_CARGA, NULL, 'SIM') 
			END
		END
		ELSE
		BEGIN
			INSERT INTO DIM_PLANO
			VALUES(@COD, @NOME, @VALOR,@DATA_CARGA, NULL, 'SIM') 
		END

		FETCH C_PLANO INTO @COD, @NOME, @VALOR
	END
	CLOSE C_PLANO
	DEALLOCATE C_PLANO
END

-- Teste
--UPDATE TB_PLANO
--SET VALOR_MENSAL = 100
--WHERE NOME = 'Premium'

--EXEC SP_OLTP_PLANO '20240322'

EXEC SP_DIM_PLANO '20240316'

SELECT * FROM TB_PLANO
SELECT * FROM TB_AUX_PLANO
SELECT * FROM DIM_PLANO