CREATE OR ALTER PROCEDURE SP_DIM_MODALIDADE(@DATA_CARGA DATETIME)
AS 
BEGIN
	DECLARE @COD INT, @NOME VARCHAR(45)

	DECLARE C_MODALIDADE CURSOR FOR
	SELECT COD_MODALIDADE, NOME
	FROM TB_AUX_MODALIDADE
	WHERE @DATA_CARGA = DATA_CARGA

	OPEN C_MODALIDADE
	FETCH C_MODALIDADE INTO @COD, @NOME

	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		IF EXISTS (SELECT * FROM DIM_MODALIDADE WHERE COD_MODALIDADE = @COD)
		BEGIN
			UPDATE DIM_MODALIDADE
			SET NOME = @NOME
			WHERE COD_MODALIDADE = @COD
		END
		ELSE
		BEGIN
			INSERT INTO DIM_MODALIDADE
			VALUES(@COD, @NOME)
		END
		FETCH C_MODALIDADE INTO @COD, @NOME
	END

	CLOSE C_MODALIDADE
	DEALLOCATE C_MODALIDADE
END



-- Teste

EXEC SP_DIM_MODALIDADE'20240316'

SELECT * FROM DIM_MODALIDADE
SELECT * FROM TB_AUX_MODALIDADE