CREATE OR ALTER PROCEDURE SP_DIM_UNIDADE(@DATA_CARGA DATETIME)
AS 
BEGIN
	DECLARE @COD INT, @NOME VARCHAR(45), @BAIRRO VARCHAR(45), @CIDADE VARCHAR(45), @ESTADO VARCHAR(3)

	DECLARE C_UNIDADE CURSOR FOR
	SELECT COD_UNIDADE, NOME, BAIRRO, CIDADE, ESTADO
	FROM TB_AUX_UNIDADE
	WHERE @DATA_CARGA = DATA_CARGA

	OPEN C_UNIDADE
	FETCH C_UNIDADE INTO @COD, @NOME, @BAIRRO, @CIDADE, @ESTADO

	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		IF EXISTS (SELECT * FROM DIM_UNIDADE WHERE COD_UNIDADE = @COD)
		BEGIN
			UPDATE DIM_UNIDADE
			SET NOME = @NOME,
				BAIRRO = @BAIRRO,
				CIDADE = @CIDADE,
				ESTADO = @ESTADO
			WHERE COD_UNIDADE = @COD
		END
		ELSE
		BEGIN
			INSERT INTO DIM_UNIDADE
			VALUES(@COD, @NOME, @BAIRRO, @CIDADE, @ESTADO)
		END
		FETCH C_UNIDADE INTO @COD, @NOME, @BAIRRO, @CIDADE, @ESTADO
	END

	CLOSE C_UNIDADE
	DEALLOCATE C_UNIDADE
END



-- Teste

EXEC SP_DIM_UNIDADE'20240316'

SELECT * FROM DIM_UNIDADE
SELECT * FROM TB_AUX_UNIDADE