CREATE OR ALTER PROCEDURE SP_DIM_CLIENTE(@DATA_CARGA DATETIME)
AS 
BEGIN
	DECLARE @COD INT, @NOME VARCHAR(45), @BAIRRO VARCHAR(45), @CIDADE VARCHAR(45), @ESTADO VARCHAR(3), @CPF VARCHAR(45), @DT_NASCIMENTO DATE

	DECLARE C_CLIENTE CURSOR FOR
	SELECT COD_CLIENTE, NOME, CPF, DT_NASCIMENTO, BAIRRO, CIDADE, ESTADO
	FROM TB_AUX_CLIENTE
	WHERE @DATA_CARGA = DATA_CARGA

	OPEN C_CLIENTE
	FETCH C_CLIENTE INTO @COD, @NOME, @CPF, @DT_NASCIMENTO, @BAIRRO, @CIDADE, @ESTADO

	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		IF EXISTS (SELECT * FROM DIM_CLIENTE WHERE COD_CLIENTE = @COD)
		BEGIN
			UPDATE DIM_CLIENTE
			SET NOME = @NOME,
				CPF = @CPF,
				DT_NASCIMENTO = @DT_NASCIMENTO,
				BAIRRO = @BAIRRO,
				CIDADE = @CIDADE,
				ESTADO = @ESTADO
			WHERE COD_CLIENTE = @COD
		END
		ELSE
		BEGIN
			INSERT INTO DIM_CLIENTE
			VALUES(@COD, @NOME, @CPF, @DT_NASCIMENTO, @BAIRRO, @CIDADE, @ESTADO)
		END
		FETCH C_CLIENTE INTO @COD, @NOME, @CPF, @DT_NASCIMENTO, @BAIRRO, @CIDADE, @ESTADO
	END

	CLOSE C_CLIENTE
	DEALLOCATE C_CLIENTE
END



-- Teste

EXEC SP_DIM_CLIENTE'20240316'

SELECT * FROM DIM_CLIENTE
SELECT * FROM TB_AUX_CLIENTE