CREATE OR ALTER PROCEDURE SP_DIM_PLANO(@DATA_CARGA DATETIME)
AS
BEGIN
	DECLARE @COD INT, @NOME VARCHAR(100), @VALOR NUMERIC(10,2)

	DECLARE C_PLANO CURSOR FOR 
	SELECT COD_PLANO, NOME, VALOR
	FROM TB_AUX_PLANO
	WHERE @DATA_CARGA = DATA_CARGA

	OPEN C_PLANO

	FETCH C_PLANO INTO @COD, @NOME, @VALOR

	WHILE(@@FETCH_STATUS = 0)
	BEGIN	
		IF(EXISTS(SELECT * FROM DIM_PLANO WHERE COD_PLANO = @COD))
		BEGIN
			UPDATE DIM_PLANO
			SET NOME = @NOME,
				VALOR = @VALOR
			WHERE COD_PLANO = @COD
		END
		ELSE
		BEGIN
			INSERT INTO DIM_PLANO
			VALUES(@COD, @NOME, @VALOR)
		END

		FETCH C_PLANO INTO @COD, @NOME, @VALOR
	END
	CLOSE C_PLANO
	DEALLOCATE C_PLANO
END

-- Teste

EXEC SP_DIM_PLANO '20240316'

SELECT * FROM TB_PLANO
SELECT * FROM TB_AUX_PLANO
SELECT * FROM DIM_PLANO