CREATE OR ALTER PROCEDURE SP_OLTP_MODALIDADE(@DATA_CARGA DATETIME)
AS
BEGIN
	DELETE FROM TB_AUX_MODALIDADE
	WHERE @DATA_CARGA = DATA_CARGA

	INSERT INTO TB_AUX_MODALIDADE
	SELECT @DATA_CARGA, ID, NOME
	FROM TB_MODALIDADE
END

-- TESTE

EXEC SP_OLTP_MODALIDADE '20240316'

SELECT * FROM TB_AUX_MODALIDADE
SELECT * FROM TB_MODALIDADE