CREATE OR ALTER PROCEDURE SP_OLTP_CLIENTE(@DATA_CARGA DATETIME)
AS
BEGIN
	DELETE FROM TB_AUX_CLIENTE
	WHERE @DATA_CARGA = DATA_CARGA

	INSERT INTO TB_AUX_CLIENTE
	SELECT @DATA_CARGA, ID, NOME, CPF, DT_NASCIMENTO, BAIRRO, CIDADE, ESTADO
	FROM TB_CLIENTE
END

-- TESTE

EXEC SP_OLTP_CLIENTE'20240316'

SELECT * FROM TB_AUX_CLIENTE
SELECT * FROM TB_CLIENTE