CREATE OR ALTER PROCEDURE SP_OLTP_MATRICULA(@DATA_CARGA DATETIME, @DATA_INICIAL DATETIME, @DATA_FINAL DATETIME)
AS
BEGIN
	DELETE FROM TB_AUX_MATRICULA
	WHERE @DATA_CARGA = DATA_CARGA

	INSERT INTO TB_AUX_MATRICULA
	SELECT @DATA_CARGA, ID, DT_MATRICULA, MODALIDADE_ID, CLIENTE_ID, PLANO_ID, UNIDADE_ID, DT_VENCIMENTO
	FROM TB_MATRICULA
	WHERE @DATA_INICIAL <= DT_MATRICULA AND @DATA_FINAL >= DT_MATRICULA
END

-- TESTE

EXEC SP_OLTP_MATRICULA '20240316', '20230110', '20240316'

SELECT * FROM TB_AUX_MATRICULA
SELECT * FROM TB_MATRICULA