CREATE OR ALTER PROCEDURE SP_OLTP_UNIDADE(@DATA_CARGA DATETIME)
AS
BEGIN
	DELETE FROM TB_AUX_UNIDADE
	WHERE @DATA_CARGA = DATA_CARGA

	INSERT INTO TB_AUX_UNIDADE
	SELECT @DATA_CARGA, ID, NOME, BAIRRO, CIDADE, ESTADO
	FROM TB_UNIDADE
END

-- TESTE

EXEC SP_OLTP_UNIDADE'20240316'

SELECT * FROM TB_AUX_UNIDADE
SELECT * FROM TB_UNIDADE