CREATE OR ALTER PROCEDURE SP_OLTP_PLANO(@DATA_CARGA DATETIME)
AS
BEGIN
	DELETE FROM TB_AUX_PLANO
	WHERE @DATA_CARGA = DATA_CARGA

	INSERT INTO TB_AUX_PLANO
	SELECT @DATA_CARGA, ID, NOME, VALOR_MENSAL
	FROM TB_PLANO 
END

-- TESTE

EXEC SP_OLTP_PLANO '20240316'

SELECT * FROM TB_AUX_PLANO
SELECT * FROM TB_PLANO
