USE PROJETO_ACADEMIA

-- CONSULTAS

-- Qual o número de matrículas por periodo(ANO)?
SELECT T.ANO, SUM(M.QUANTIDADE) AS QUANTIDADE_MATRICULAS
FROM FATO_MATRICULA M
INNER JOIN DIM_TEMPO T
ON(M.DATA_MATRICULA = T.ID_TEMPO)
GROUP BY T.ANO


-- Qual o número de matrículas por unidade?
SELECT U.NOME NOME_UNIDADE, SUM(M.QUANTIDADE) AS QUANTIDADE_MATRICULAS 
FROM FATO_MATRICULA M
INNER JOIN DIM_UNIDADE U
ON(M.UNIDADE_ID = U.ID_UNIDADE)
GROUP BY U.NOME


-- Qual o número de matrículas por bairro?
SELECT C.BAIRRO, SUM(M.QUANTIDADE) AS QUANTIDADE_MATRICULAS 
FROM FATO_MATRICULA M
INNER JOIN DIM_CLIENTE C
ON(M.CLIENTE_ID = C.ID_CLIENTE)
GROUP BY C.BAIRRO


-- Qual o número de matrículas por modalidade?
SELECT MO.NOME AS MODALIDADE, SUM(M.QUANTIDADE) AS QUANTIDADE_MATRICULAS 
FROM FATO_MATRICULA M
INNER JOIN DIM_MODALIDADE MO
ON(M.MODALIDADE_ID = MO.ID_MODALIDADE)
GROUP BY MO.NOME


-- Qual o total de pagamentos por período em determinada unidade?
SELECT SUM(P.VALOR) AS TOTAL_PAGAMENTOS, T.ANO, U.NOME
FROM FATO_PAGAMENTO P
INNER JOIN DIM_UNIDADE U
ON(P.UNIDADE_ID = U.ID_UNIDADE)
INNER JOIN DIM_TEMPO T
ON(P.DATA_PAGAMENTO = T.ID_TEMPO)
GROUP BY T.ANO, U.NOME


-- Qual o número de matrículas por plano por ano?
SELECT T.ANO, P.NOME AS PLANO, SUM(M.QUANTIDADE) AS QUANTIDADE_MATRICULAS 
FROM FATO_MATRICULA M
INNER JOIN DIM_PLANO P
ON(M.PLANO_ID = P.ID_PLANO)
INNER JOIN DIM_TEMPO T
ON(M.DATA_MATRICULA = T.ID_TEMPO)
WHERE T.ANO = 2023
GROUP BY T.ANO, P.NOME


-- Qual o número de pagamentos em atraso?
SELECT SUM(P.QUANTIDADE) AS 'PAGAMENTOS EM ATRASO'
FROM FATO_PAGAMENTO P
INNER JOIN DIM_STATUS S
ON(P.STATUS_ID = S.ID_STATUS)
WHERE S.NOME = 'EM ATRASO'


-- Qual o número de clientes no turno da manhã em um determinado dia?
SELECT SUM(F.QUANTIDADE) AS NUMERO_DE_CLIENTES
FROM FATO_FREQUENCIA F
INNER JOIN DIM_TEMPO TE
ON(F.DATA_FREQUENCIA = TE.ID_TEMPO)
INNER JOIN DIM_TURNO TU
ON(TU.ID_TURNO = F.TURNO_ID)
WHERE (TU.NOME = 'MANHA') AND (TE.DATA = GETDATE())


-- Qual o número de clientes no turno da tarde em um determinado dia?
SELECT SUM(F.QUANTIDADE) AS NUMERO_DE_CLIENTES
FROM FATO_FREQUENCIA F
INNER JOIN DIM_TEMPO TE
ON(F.DATA_FREQUENCIA = TE.ID_TEMPO)
INNER JOIN DIM_TURNO TU
ON(TU.ID_TURNO = F.TURNO_ID)
WHERE (TU.NOME = 'TARDE') AND (TE.DATA = GETDATE())


-- Qual o tempo médio de duração de matrícula?
SELECT AVG(DATEDIFF(MONTH, T1.DATA, T2.DATA)) AS MEDIA_DE_DURACAO
FROM FATO_MATRICULA M
INNER JOIN DIM_TEMPO T1
ON(M.DATA_MATRICULA = T1.ID_TEMPO)
INNER JOIN DIM_TEMPO T2
ON(M.DATA_VENCIMENTO = T2.ID_TEMPO)


-- Qual a modalidade que possui mais matrículas?
SELECT MD.NOME AS MODALIDADE, SUM(MT.QUANTIDADE) AS QUANTIDADE_MATRICULAS
FROM FATO_MATRICULA MT
INNER JOIN DIM_MODALIDADE MD
ON(MT.MODALIDADE_ID = MD.ID_MODALIDADE)
GROUP BY MD.NOME
ORDER BY QUANTIDADE_MATRICULAS DESC