USE ACADEMIA

-- Inserção de dados na tabela Matricula
CREATE PROCEDURE SP_INCLUI_MATRICULA (@QuantidadeClientes INT,
									  @QuantidadeUnidades INT,
									  @QuantidadeModalidades INT,
									  @QuantidadePlanos INT,
									  @QuantidadeMatriculas INT)
AS
BEGIN
	DECLARE @i INT = 1
	DECLARE @DT_VENC DATE, @DT_MAT DATE
	-- Popula a tabela TB_MATRICULA
    SET @i = 1
    WHILE @i <= @QuantidadeMatriculas
    BEGIN
		SET @DT_MAT = DATEADD(DAY, -FLOOR(RAND() * 365), GETDATE())
		SET @DT_VENC = DATEADD(MONTH, FLOOR(RAND() * 12), @DT_MAT)

        INSERT INTO TB_MATRICULA (DT_MATRICULA, DT_VENCIMENTO, CLIENTE_ID, UNIDADE_ID, MODALIDADE_ID, PLANO_ID)
        VALUES (@DT_MAT, @DT_VENC, FLOOR(RAND() * @QuantidadeClientes) + 1, FLOOR(RAND() * @QuantidadeUnidades) + 1, FLOOR(RAND() * @QuantidadeModalidades) + 1, FLOOR(RAND() * @QuantidadePlanos) + 1)
        SET @i = @i + 1
    END
END 

-- Inserção de dados na tabela Pagamento
CREATE OR ALTER PROCEDURE SP_INCLUI_PAGAMENTO
AS BEGIN

	DECLARE @ID INT, @DT_MATRICULA DATE, @DT_VENCIMENTO DATE, @PLANO INT, @QTD_PAG INT, @VALOR NUMERIC(10,2)
	DECLARE @I INT

	DECLARE C_MATRICULAS CURSOR 
	FOR SELECT ID, DT_MATRICULA, DT_VENCIMENTO, PLANO_ID
	FROM TB_MATRICULA

	OPEN C_MATRICULAS 
	FETCH C_MATRICULAS INTO @ID, @DT_MATRICULA, @DT_VENCIMENTO, @PLANO
	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		SET @QTD_PAG = DATEDIFF(MONTH, @DT_MATRICULA, @DT_VENCIMENTO)
		SET @I = 0
		SELECT @VALOR = VALOR_MENSAL
		FROM TB_PLANO
		WHERE ID = @PLANO

		WHILE @I < @QTD_PAG
		BEGIN
			INSERT INTO TB_PAGAMENTO (DT_PREVISTA, DT_PAGAMENTO, VALOR_PAGO, MATRICULA_ID)
			VALUES (DATEADD(MONTH, @I, @DT_MATRICULA), DATEADD(MONTH, @I, @DT_MATRICULA), @VALOR, @ID)
			SET @I = @I + 1
		END
		FETCH C_MATRICULAS INTO @ID, @DT_MATRICULA, @DT_VENCIMENTO, @PLANO
	END
	CLOSE C_MATRICULAS
	DEALLOCATE C_MATRICULAS
END

EXEC SP_INCLUI_PAGAMENTO

-- Inserção de dados na tabela Frequencia
CREATE OR ALTER PROCEDURE SP_INCLUI_FREQUENCIAS (@QUANTIDADE_DIAS INT)
AS
BEGIN
    DECLARE @CONTADOR INT, @ID_CLIENTE INT, @TEMP INT
    DECLARE @DATA_MATRICULA DATE, @DATA DATE, @DATA_VENCIMENTO DATE
	DECLARE @ENTRADA TIME, @SAIDA TIME

    SET @CONTADOR = 1

    DECLARE C_MATRICULA CURSOR FOR
    SELECT DT_MATRICULA, CLIENTE_ID, DT_VENCIMENTO
    FROM TB_MATRICULA

    OPEN C_MATRICULA

    FETCH C_MATRICULA INTO @DATA_MATRICULA, @ID_CLIENTE, @DATA_VENCIMENTO

    WHILE(@@FETCH_STATUS = 0)
    BEGIN
        WHILE @CONTADOR <= @QUANTIDADE_DIAS
        BEGIN

            IF @CONTADOR % 3 = 1 -- Turno da manhã
            BEGIN
                SET @TEMP = FLOOR(RAND(CHECKSUM(NEWID())) * (12 - 8 + 1)) + 8
                SET @SAIDA = CAST(FLOOR(RAND(CHECKSUM(NEWID())) * (12 - (@TEMP+1) + 1)) + (@TEMP+1) AS VARCHAR) + ':00:00'
				SET @ENTRADA = CAST(@TEMP AS VARCHAR) + ':00:00'
            END
            ELSE IF @CONTADOR % 3 = 2 -- Turno da tarde
            BEGIN
                SET @TEMP = FLOOR(RAND(CHECKSUM(NEWID())) * (18 - 13 + 1)) + 13 
                SET @SAIDA = CAST(FLOOR(RAND(CHECKSUM(NEWID())) * (18 - (@TEMP+1) + 1)) + (@TEMP+1) AS VARCHAR) + ':00:00'
				SET @ENTRADA = CAST(@TEMP AS VARCHAR) + ':00:00'
            END
            ELSE -- Turno da noite
            BEGIN
                SET @TEMP = FLOOR(RAND(CHECKSUM(NEWID())) * (22 - 19 + 1)) + 19 
                SET @SAIDA = CAST(FLOOR(RAND(CHECKSUM(NEWID())) * (22 - (@TEMP+1) + 1)) + (@TEMP+1) AS VARCHAR) + ':00:00'
				SET @ENTRADA = CAST(@TEMP AS VARCHAR) + ':00:00'
            END
			SET @DATA = DATEADD(DAY, @CONTADOR -1, @DATA_MATRICULA)
			IF (@DATA <= @DATA_VENCIMENTO)
			BEGIN
				INSERT INTO TB_FREQUENCIA 
				VALUES(@DATA, @ENTRADA, @SAIDA, @ID_CLIENTE)
				SET @CONTADOR = @CONTADOR + 1
			END
            ELSE
			BEGIN
				SET @CONTADOR = @QUANTIDADE_DIAS +1
			END
        END

        SET @CONTADOR = 1

        FETCH C_MATRICULA INTO @DATA_MATRICULA, @ID_CLIENTE, @DATA_VENCIMENTO
    END

    CLOSE C_MATRICULA
    DEALLOCATE C_MATRICULA
END

EXEC SP_INCLUI_FREQUENCIAS 10

DELETE FROM TB_FREQUENCIA

SELECT * FROM TB_MATRICULA
SELECT * FROM TB_FREQUENCIA
SELECT * FROM TB_PAGAMENTO

