DROP DATABASE PROJETO_ACADEMIA
CREATE DATABASE PROJETO_ACADEMIA
USE PROJETO_ACADEMIA

-- DIMENSÕES

CREATE TABLE DIM_TEMPO (
	ID_TEMPO INT PRIMARY KEY IDENTITY(1,1),
	DATA DATE NOT NULL,
	DIA INT NOT NULL,
	MES INT NOT NULL,
	NOME_MES VARCHAR(45) NOT NULL,
	SEMESTRE INT NOT NULL,
	ANO INT NOT NULL
);

CREATE TABLE DIM_CLIENTE (
    ID_CLIENTE INT PRIMARY KEY IDENTITY(1,1),
	COD_CLIENTE INT NOT NULL,
    NOME VARCHAR(45) NOT NULL,
    CPF VARCHAR(15) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    BAIRRO VARCHAR(45) NOT NULL,
    CIDADE VARCHAR(45) NOT NULL,
    ESTADO VARCHAR(3) NOT NULL
);

CREATE TABLE DIM_UNIDADE (
    ID_UNIDADE INT PRIMARY KEY IDENTITY(1,1),
	COD_UNIDADE INT NOT NULL,
    NOME VARCHAR(45) NOT NULL,
    BAIRRO VARCHAR(45) NOT NULL,
    CIDADE VARCHAR(45) NOT NULL,
    ESTADO VARCHAR(3) NOT NULL
);

CREATE TABLE DIM_MODALIDADE (
    ID_MODALIDADE INT PRIMARY KEY IDENTITY(1,1),
	COD_MODALIDADE INT NOT NULL,
    NOME VARCHAR(45) NOT NULL
);

CREATE TABLE DIM_PLANO (
    ID_PLANO INT PRIMARY KEY IDENTITY(1,1),
	COD_PLANO INT NOT NULL,
    NOME VARCHAR(45) NOT NULL,
    VALOR FLOAT NOT NULL
);

CREATE TABLE DIM_STATUS (
    ID_STATUS INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(10) NOT NULL CHECK (NOME IN ('EM ATRASO','PAGO'))
);

CREATE TABLE DIM_TURNO (
    ID_TURNO INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(10) NOT NULL CHECK (NOME IN ('MANHA','TARDE','NOITE'))
);


-- FATOS

CREATE TABLE FATO_MATRICULA (
    ID_MATRICULA INT PRIMARY KEY IDENTITY(1,1),
	COD_MATRICULA INT NOT NULL,
	QUANTIDADE INT NOT NULL,
    CLIENTE_ID INT NOT NULL,
    UNIDADE_ID INT NOT NULL,
    MODALIDADE_ID INT NOT NULL,
    PLANO_ID INT NOT NULL,
	DATA_MATRICULA INT NOT NULL,
	DATA_VENCIMENTO INT NOT NULL,
    CONSTRAINT FK_MATRICULA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES DIM_CLIENTE (ID_CLIENTE),
    CONSTRAINT FK_MATRICULA_UNIDADE FOREIGN KEY (UNIDADE_ID) REFERENCES DIM_UNIDADE (ID_UNIDADE),
    CONSTRAINT FK_MATRICULA_MODALIDADE FOREIGN KEY (MODALIDADE_ID) REFERENCES DIM_MODALIDADE (ID_MODALIDADE),
    CONSTRAINT FK_MATRICULA_PLANO FOREIGN KEY (PLANO_ID) REFERENCES DIM_PLANO (ID_PLANO),
	CONSTRAINT FK_MATRICULA_DATA_MATRICULA FOREIGN KEY (DATA_MATRICULA) REFERENCES DIM_TEMPO (ID_TEMPO),
	CONSTRAINT FK_MATRICULA_DATA_VECIMENTO FOREIGN KEY (DATA_VENCIMENTO) REFERENCES DIM_TEMPO (ID_TEMPO)
);

CREATE TABLE FATO_PAGAMENTO (
    ID_PAGAMENTO INT PRIMARY KEY IDENTITY(1,1),
	COD_PAGAMENTO INT NOT NULL,
    VALOR FLOAT NOT NULL,
	QUANTIDADE INT NOT NULL,
	STATUS_ID INT NULL,
    UNIDADE_ID INT NOT NULL,
	PLANO_ID INT NOT NULL,
	DATA_PREVISTA INT NOT NULL,
	DATA_PAGAMENTO INT NULL,
	CONSTRAINT FK_PAGAMENTO_STATUS FOREIGN KEY (STATUS_ID) REFERENCES DIM_STATUS (ID_STATUS),
    CONSTRAINT FK_PAGAMENTO_UNIDADE FOREIGN KEY (UNIDADE_ID) REFERENCES DIM_UNIDADE (ID_UNIDADE),
	CONSTRAINT FK_PAGAMENTO_PLANO FOREIGN KEY (PLANO_ID) REFERENCES DIM_PLANO (ID_PLANO),
	CONSTRAINT FK_PAGAMENTO_DATA_PREVISTA FOREIGN KEY (DATA_PREVISTA) REFERENCES DIM_TEMPO (ID_TEMPO),
	CONSTRAINT FK_PAGAMENTO_DATA_PAGAMENTO FOREIGN KEY (DATA_PAGAMENTO) REFERENCES DIM_TEMPO (ID_TEMPO)
);

CREATE TABLE FATO_FREQUENCIA (
    ID_FREQUENCIA INT PRIMARY KEY IDENTITY(1,1),
	COD_FREQUENCIA INT NOT NULL,
    ENTRADA TIME NOT NULL,
    SAIDA TIME NOT NULL,
	QUANTIDADE INT NOT NULL,
	TURNO_ID INT NOT NULL,
	DATA_FREQUENCIA INT NOT NULL,
	CLIENTE_ID INT NOT NULL,
	CONSTRAINT FK_FREQUENCIA_TURNO FOREIGN KEY (TURNO_ID) REFERENCES DIM_TURNO (ID_TURNO),
	CONSTRAINT FK_FREQUENCIA_TEMPO FOREIGN KEY (DATA_FREQUENCIA) REFERENCES DIM_TEMPO (ID_TEMPO),
    CONSTRAINT FK_FREQUENCIA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES DIM_CLIENTE (ID_CLIENTE)
);


