-- Criação do esquema e uso do banco de dados

USE ACADEMIA;


-- Tabelas
DROP TABLE TB_CLIENTE
DROP TABLE TB_FREQUENCIA
DROP TABLE TB_EQUIPAMENTO
DROP TABLE TB_FUNCIONARIO
DROP TABLE TB_MATRICULA
DROP TABLE TB_MODALIDADE
DROP TABLE TB_PAGAMENTO
DROP TABLE TB_PLANO
DROP TABLE TB_UNIDADE

CREATE TABLE TB_CLIENTE (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(45) NOT NULL,
    TELEFONE VARCHAR(20) NULL,
    SEXO VARCHAR(10) NULL,
    CPF VARCHAR(15) NULL,
    DT_NASCIMENTO DATE NOT NULL,
    EMAIL VARCHAR(45) NOT NULL,
    BAIRRO VARCHAR(45) NOT NULL,
    CIDADE VARCHAR(45) NOT NULL,
    ESTADO VARCHAR(3) NOT NULL,
    RUA VARCHAR(45) NOT NULL,
    CASA_NUMERO VARCHAR(6) NOT NULL
);

INSERT INTO TB_CLIENTE
VALUES('João Silva', '79999999996', 'Masculino', '123.456.789-01', '1990-05-15', 'joao@email.com', 'Centro', 'Itabaiana', 'SE', 'Rua A', '123')
INSERT INTO TB_CLIENTE
VALUES('Maria Oliveira', '79999999997', 'Feminino', '987.654.321-02', '1985-10-20', 'maria@email.com', 'Bairro B', 'Ribeirópolis', 'SE', 'Rua B', '456')
INSERT INTO TB_CLIENTE
VALUES('Janaina Ferreira', '79999999999', 'Feminino', '123.789.456-03', '1999-11-03', 'janaina@gmail.com', 'Mamede Paes Mendonça', 'Itabaiana', 'SE', 'Rua Euclides', '100')
INSERT INTO TB_CLIENTE
VALUES('Josefa Santos','79998473268', 'Feminino','234.854.921-04', '1970-12-10','josefa@gmail.com', 'Bairro Novo Horizonte', 'Lagarto', 'SE', 'Rua Limoeiro', 's/n')
INSERT INTO TB_CLIENTE
VALUES('Antônio Almeida', null, 'Masculino', '198.847.584-05', '1995-07-03', 'almeida@gmail.com', 'Bairro C', 'Ribeirópolis', 'SE', 'Rua C', '200')
INSERT INTO TB_CLIENTE
VALUES('Laura Alves','79993028467','Feminino','293.853.953-06', '2004-05-30', 'laura@gmail.com','Centro','Itabaiana','SE','Rua 7 de Setembro','50')
INSERT INTO TB_CLIENTE
VALUES('Pedro Batista', '79990654734', 'Masculino', '196.390.276-07', '2000-03-25', 'Pe@gmail.com', 'Serrano', 'Itabaiana', 'SE', 'Rua G', '150')

CREATE TABLE TB_UNIDADE (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(45) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    BAIRRO VARCHAR(45) NOT NULL,
    CIDADE VARCHAR(45) NOT NULL,
    ESTADO VARCHAR(3) NOT NULL,
    RUA VARCHAR(45) NOT NULL,
    NUMERO VARCHAR(6) NOT NULL
);

INSERT INTO TB_UNIDADE
VALUES('Unidade Principal', '111222333', 'Centro', 'Itabaiana', 'SE', 'Rua Principal', '789')
INSERT INTO TB_UNIDADE
VALUES('Filial A', '444555666', 'Bairro A', 'Ribeieropolis', 'SE', 'Rua Filial A', '101')
INSERT INTO TB_UNIDADE
VALUES('Filial B', '384728493', 'Bairro Novo Horizonte', 'Lagarto', 'SE', 'Rua Horizonte', '130')
INSERT INTO TB_UNIDADE
VALUES('Unidade 2', '79 99999999', 'Chiara', 'Itabaiana', 'SE', 'Rua Principal', '75')

CREATE TABLE TB_MODALIDADE (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(45) NOT NULL,
    QUANTIDADE_SEMANA INT NULL
);

INSERT INTO TB_MODALIDADE
VALUES('Musculação', 5)
INSERT INTO TB_MODALIDADE
VALUES('Funcional', 3)
INSERT INTO TB_MODALIDADE
VALUES('Pilates', 5)

CREATE TABLE TB_PLANO (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(45) NOT NULL,
    VALOR_MENSAL NUMERIC(10,2) NOT NULL
);

INSERT INTO TB_PLANO
VALUES('Básico', 70.00)
INSERT INTO TB_PLANO
VALUES('Premium', 90.00)


CREATE TABLE TB_FUNCIONARIO (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(45) NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    CARGO VARCHAR(45) NOT NULL,
    SALARIO NUMERIC(10,2) NULL,
    DT_NASCIMENTO DATE NOT NULL,
    CPF VARCHAR(15) NOT NULL,
    DT_ADMISSAO DATE NOT NULL,
    DT_DEMISSAO DATE NULL,
    UNIDADE_ID INT NOT NULL,
    BAIRRO VARCHAR(45) NOT NULL,
    CIDADE VARCHAR(45) NOT NULL,
    ESTADO VARCHAR(3) NOT NULL,
    RUA VARCHAR(45) NOT NULL,
    NUMERO VARCHAR(6) NOT NULL,
    CONSTRAINT FK_FUNCIONARIO_UNIDADE FOREIGN KEY (UNIDADE_ID) REFERENCES TB_UNIDADE (ID)
);

INSERT INTO TB_FUNCIONARIO
VALUES('Carlos Santos', 'carlos@email.com', '555666777', 'Instrutor', 3000.00, '1980-08-10', '345.678.901-23', '2020-01-01', NULL, 1, 'Santa Mônica', 'Itabaiana', 'SE', 'Rua C', '987')
INSERT INTO TB_FUNCIONARIO
VALUES('Ana Pereira', 'ana@email.com', '999888777', 'Recepcionista', 2500.00, '1992-03-25', '876.543.210-98', '2022-05-01', NULL, 2, 'Centro', 'Ribeirópolis', 'SE', 'Rua Josué Passos', '202')
INSERT INTO TB_FUNCIONARIO
VALUES('Lorena Lisboa', 'lore@gmail.com', '993827942', 'Instrutora', 3000.00, '1990-12-30', '938.847.292-93', '2022-10-20', NULL, 2, 'Centro', 'Ribeirópolis','SE', 'Rua Felino Bofim', '96')
INSERT INTO TB_FUNCIONARIO
VALUES('Arthur Andrade', 'arthur@gmail.com', '998367215', 'Recepcionista', 2500.00, '1990-03-19', '159.029.493-20', '2021-10-20', NULL, 1, 'Serrano', 'Itabaiana', 'SE', 'Rua Itaporanga', '40')
INSERT INTO TB_FUNCIONARIO
VALUES('Gustavo Dias', 'gus@gmail.com', '994803826', 'Instrutor', 3000.00, '1987-10-20', '194.938.743-09', '2020-04-19', NULL, 3, 'Novo Horizonte', 'Lagarto', 'SE', 'Rua G', '100')

CREATE TABLE TB_EQUIPAMENTO (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(45) NOT NULL,
    DESCRICAO VARCHAR(45) NULL,
    DT_AQUISICAO DATE NOT NULL,
    QUANTIDADE INT NOT NULL,
    UNIDADE_ID INT NOT NULL,
    CONSTRAINT FK_EQUIPAMENTO_UNIDADE FOREIGN KEY (UNIDADE_ID) REFERENCES TB_UNIDADE (ID)
);

INSERT INTO TB_EQUIPAMENTO
VALUES('Esteira', 'Esteira para corrida', '2023-01-01', 5, 1)
INSERT INTO TB_EQUIPAMENTO
VALUES('Bicicleta Ergométrica', 'Bicicleta para exercícios cardiovasculares', '2023-02-01', 3, 2)
INSERT INTO TB_EQUIPAMENTO
VALUES('Esteira', 'Esteira para corrida', '2023-02-01', 3, 2)
INSERT INTO TB_EQUIPAMENTO
VALUES('Bicicleta Ergométrica', 'Bicicleta para exercícios cardiovasculares', '2023-01-01', 3, 1)
INSERT INTO TB_EQUIPAMENTO
VALUES('Esteira', 'Esteira para corrida', '2023-01-01', 3, 3)
INSERT INTO TB_EQUIPAMENTO
VALUES('Bicicleta Ergométrica', 'Bicicleta para exercícios cardiovasculares', '2023-02-01', 3, 3)
INSERT INTO TB_EQUIPAMENTO
VALUES('Leg Press', 'Musculatura das pernas', '2023-01-01', 4, 1)
INSERT INTO TB_EQUIPAMENTO
VALUES('Leg Press', 'Musculatura das pernas', '2023-01-01', 2, 2)
INSERT INTO TB_EQUIPAMENTO
VALUES('Leg Press', 'Musculatura das pernas', '2023-01-01', 2, 3)

CREATE TABLE TB_MATRICULA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    DT_MATRICULA DATE NOT NULL,
    DT_VENCIMENTO DATE NOT NULL,
    CLIENTE_ID INT NOT NULL,
    UNIDADE_ID INT NOT NULL,
    MODALIDADE_ID INT NOT NULL,
    PLANO_ID INT NOT NULL,
    CONSTRAINT FK_MATRICULA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES TB_CLIENTE (ID),
    CONSTRAINT FK_MATRICULA_UNIDADE FOREIGN KEY (UNIDADE_ID) REFERENCES TB_UNIDADE (ID),
    CONSTRAINT FK_MATRICULA_MODALIDADE FOREIGN KEY (MODALIDADE_ID) REFERENCES TB_MODALIDADE (ID),
    CONSTRAINT FK_MATRICULA_PLANO FOREIGN KEY (PLANO_ID) REFERENCES TB_PLANO (ID)
);

CREATE TABLE TB_PAGAMENTO (
    ID INT PRIMARY KEY IDENTITY(1,1),
	DT_PREVISTA DATE NOT NULL,
    DT_PAGAMENTO DATE NULL,
    VALOR_PAGO NUMERIC(10,2) NOT NULL,
    MATRICULA_ID INT NOT NULL,
    CONSTRAINT FK_PAGAMENTO_MATRICULA FOREIGN KEY (MATRICULA_ID) REFERENCES TB_MATRICULA (ID)
);

CREATE TABLE TB_FREQUENCIA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    DT_FREQUENCIA DATE NULL,
    ENTRADA TIME NULL,
    SAIDA TIME NULL,
    CLIENTE_ID INT NOT NULL,
    CONSTRAINT FK_FREQUENCIA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES TB_CLIENTE (ID)
);