USE ACADEMIA

DROP TABLE TB_AUX_MATRICULA
DROP TABLE TB_AUX_PAGAMENTO
DROP TABLE TB_AUX_CLIENTE
DROP TABLE TB_AUX_UNIDADE 
DROP TABLE TB_AUX_MODALIDADE
DROP TABLE TB_AUX_PLANO
DROP TABLE TB_AUX_FREQUENCIA

CREATE TABLE TB_AUX_MATRICULA (
  DATA_CARGA DATE NOT NULL,
  COD_MATRICULA INT NULL,
  DATA_MATRICULA DATE NULL,
  COD_MODALIDADE INT NULL,
  COD_CLIENTE INT NULL,
  COD_PLANO INT NULL,
  COD_UNIDADE INT NULL,
  DATA_VENCIMENTO DATE NULL)

CREATE TABLE TB_AUX_FREQUENCIA (
  DATA_CARGA DATE NOT NULL,
  ENTRADA TIME NULL,
  SAIDA TIME NULL,
  COD_FREQUENCIA INT NULL,
  DATA_FREQUENCIA DATE NULL,
  COD_CLIENTE INT NULL)

CREATE TABLE TB_AUX_PAGAMENTO (
  DATA_CARGA DATE NOT NULL,
  VALOR NUMERIC(10,2) NULL,
  COD_PAGAMENTO INT NULL,
  DATA_PAGAMENTO DATE NULL,
  COD_UNIDADE INT NULL,
  COD_PLANO INT NULL,
  DATA_PREVISTA DATE NULL)

CREATE TABLE TB_AUX_CLIENTE (
  DATA_CARGA DATE NOT NULL,
  COD_CLIENTE INT NULL,
  NOME VARCHAR(45) NULL,
  CPF VARCHAR(45) NULL,
  DT_NASCIMENTO DATE NULL,
  BAIRRO VARCHAR(45) NULL,
  CIDADE VARCHAR(45) NULL,
  ESTADO VARCHAR(45) NULL)

CREATE TABLE TB_AUX_UNIDADE (
  DATA_CARGA DATE NOT NULL,
  COD_UNIDADE INT NULL,
  NOME VARCHAR(45) NULL,
  BAIRRO VARCHAR(45) NULL,
  CIDADE VARCHAR(45) NULL,
  ESTADO VARCHAR(45) NULL)

CREATE TABLE TB_AUX_MODALIDADE (
  DATA_CARGA DATE NOT NULL,
  COD_MODALIDADE INT NULL,
  NOME VARCHAR(45) NULL)

CREATE TABLE TB_AUX_PLANO (
  DATA_CARGA DATE NOT NULL,
  COD_PLANO INT NULL,
  NOME VARCHAR(45) NULL,
  VALOR NUMERIC(10,2) NULL)

