USE ACADEMIA

DROP TABLE TB_AUX_MATRICULA
DROP TABLE TB_AUX_PAGAMENTO
DROP TABLE TB_AUX_CLIENTE
DROP TABLE TB_AUX_UNIDADE 
DROP TABLE TB_AUX_MODALIDADE
DROP TABLE TB_AUX_PLANO
DROP TABLE TB_AUX_FREQUENCIA

CREATE TABLE TB_AUX_MATRICULA (
  DATA_CARGA DATETIME NOT NULL,
  COD_MATRICULA INT NULL,
  DATA_MATRICULA DATE NULL,
  COD_MODALIDADE INT NULL,
  COD_CLIENTE INT NULL,
  COD_PLANO INT NULL,
  COD_UNIDADE INT NULL,
  DATA_VENCIMENTO DATE NULL)

CREATE TABLE TB_AUX_FREQUENCIA (
  DATA_CARGA DATETIME NOT NULL,
  ENTRADA TIME NULL,
  SAIDA TIME NULL,
  COD_FREQUENCIA INT NULL,
  DATA_FREQUENCIA DATE NULL,
  COD_CLIENTE INT NULL)

CREATE TABLE TB_AUX_PAGAMENTO (
  DATA_CARGA DATETIME NOT NULL,
  VALOR NUMERIC(10,2) NULL,
  COD_PAGAMENTO INT NULL,
  DATA_PAGAMENTO DATE NULL,
  COD_UNIDADE INT NULL,
  COD_PLANO INT NULL,
  DATA_PREVISTA DATE NULL)

CREATE TABLE TB_AUX_CLIENTE (
  DATA_CARGA DATETIME NOT NULL,
  COD_CLIENTE INT NULL,
  NOME VARCHAR(45) NULL,
  CPF VARCHAR(45) NULL,
  DT_NASCIMENTO DATE NULL,
  BAIRRO VARCHAR(45) NULL,
  CIDADE VARCHAR(45) NULL,
  ESTADO VARCHAR(45) NULL)

CREATE TABLE TB_AUX_UNIDADE (
  DATA_CARGA DATETIME NOT NULL,
  COD_UNIDADE INT NULL,
  NOME VARCHAR(45) NULL,
  BAIRRO VARCHAR(45) NULL,
  CIDADE VARCHAR(45) NULL,
  ESTADO VARCHAR(45) NULL)

CREATE TABLE TB_AUX_MODALIDADE (
  DATA_CARGA DATETIME NOT NULL,
  COD_MODALIDADE INT NULL,
  NOME VARCHAR(45) NULL)

CREATE TABLE TB_AUX_PLANO (
  DATA_CARGA DATETIME NOT NULL,
  COD_PLANO INT NULL,
  NOME VARCHAR(45) NULL,
  VALOR NUMERIC(10,2) NULL)

  -- Tabelas de Violações

CREATE TABLE TB_VIO_PAGAMENTO (
    ID_VIO_PAGAMENTO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DATA_CARGA DATETIME NOT NULL,
	VALOR NUMERIC(10,2) NULL,
	COD_PAGAMENTO INT NULL,
	DATA_PAGAMENTO DATE NULL,
	COD_UNIDADE INT NULL,
	COD_PLANO INT NULL,
	DATA_PREVISTA DATE NULL,
	DT_ERRO DATETIME NOT NULL,
    VIOLACAO VARCHAR(150) NOT NULL)

CREATE TABLE TB_VIO_MATRICULA (
    ID_VIO_MATRICULA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DATA_CARGA DATETIME NOT NULL,
	COD_MATRICULA INT NULL,
	DATA_MATRICULA DATE NULL,
	COD_MODALIDADE INT NULL,
	COD_CLIENTE INT NULL,
	COD_PLANO INT NULL,
	COD_UNIDADE INT NULL,
	DATA_VENCIMENTO DATE NULL,
	DT_ERRO DATETIME NOT NULL,
    VIOLACAO VARCHAR(150) NOT NULL)

CREATE TABLE TB_VIO_FREQUENCIA(
	ID_VIO_FREQUENCIA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DATA_CARGA DATETIME NOT NULL,
	DATA_FREQUENCIA DATE NULL,
	COD_CLIENTE INT NULL,
	DT_ERRO DATETIME NOT NULL,
    VIOLACAO VARCHAR(150) NOT NULL
)