-- Script para povoar a dimensão tempo

USE ACADEMIA

CREATE OR ALTER PROCEDURE SP_DIM_TEMPO(@DT_INICIAL DATE, @DT_FINAL DATE)
AS
BEGIN
	SET LANGUAGE BRAZILIAN
	DECLARE @FIM_SEMANA VARCHAR(4), @TRIMESTRE INT, @SEMESTRE INT, @NM_TRIMESTRE VARCHAR(30), @NM_SEMESTRE VARCHAR(30), @DT_ANTERIOR DATE
	WHILE(@DT_FINAL>=@DT_INICIAL)
	BEGIN
		IF (DATENAME(DW, @DT_INICIAL) = 'Sabado') or (DATENAME(DW, @DT_INICIAL) = 'Domingo')
			SET @FIM_SEMANA = 'SIM'
		ELSE
			SET @FIM_SEMANA = 'NAO'
		
		IF DATEPART(MM, @DT_INICIAL) <= 3
			SET @TRIMESTRE = 1
		ELSE
			IF DATEPART(MM, @DT_INICIAL) > 3 AND DATEPART(MM, @DT_INICIAL) <= 6
				SET @TRIMESTRE = 2
			ELSE
				IF DATEPART(MM, @DT_INICIAL) > 6 AND DATEPART(MM, @DT_INICIAL) <= 9
					SET @TRIMESTRE = 3
				ELSE
					SET @TRIMESTRE = 4
		SET @NM_TRIMESTRE = CONCAT(@TRIMESTRE, '° Trimestre/',  DATEPART(YYYY, @DT_INICIAL))

		IF DATEPART(MM, @DT_INICIAL) <= 6
			SET @SEMESTRE = 1
		ELSE
			SET @SEMESTRE = 2
		SET @NM_SEMESTRE = CONCAT(@SEMESTRE, '° Semestre/', DATEPART(YYYY, @DT_INICIAL))

		INSERT INTO DIM_TEMPO
		VALUES('DIA', @DT_INICIAL, DATEPART(DD, @DT_INICIAL), DATENAME(DW, @DT_INICIAL), @FIM_SEMANA, DATEPART(MM, @DT_INICIAL), DATENAME(MM, @DT_INICIAL), @TRIMESTRE, @NM_TRIMESTRE, @SEMESTRE, @NM_SEMESTRE, DATEPART(YYYY, @DT_INICIAL))
		SET @DT_ANTERIOR = @DT_INICIAL
		SET @DT_INICIAL = DATEADD(DD, 1, @DT_INICIAL)

		IF (DATEPART(MM, @DT_ANTERIOR) != DATEPART(MM, @DT_INICIAL))
			INSERT INTO DIM_TEMPO
			VALUES('MES', NULL, NULL, NULL, NULL, DATEPART(MM, @DT_ANTERIOR), DATENAME(MM, @DT_ANTERIOR), @TRIMESTRE, @NM_TRIMESTRE, @SEMESTRE, @NM_SEMESTRE, DATEPART(YYYY, @DT_ANTERIOR))

		IF (DATEPART(YYYY, @DT_ANTERIOR) != DATEPART(YYYY, @DT_INICIAL))
			INSERT INTO DIM_TEMPO
			VALUES('ANO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, DATEPART(YYYY, @DT_ANTERIOR))
	END
END

EXEC SP_DIM_TEMPO '20230110', '20241231'

SELECT * FROM DIM_TEMPO